### ISSUE TITLE
wp.media.frame.on is undefined

### ISSUE THREAD

**Issue by Cicciokr** [emandiev/woo-image-seo#1]
Hi, in the elementor edit page the wp.media.frame object not exists, and if you change with wp.media.frames the object is empty, and the jquery listener "on" broke the page.
Now i have resolved with try {} catch() {} to override the error on the file views/media-popup.php

**Comment by emandiev** [comment]
Hi

Thanks for the feedback!

I added a simple check to ensure that `wp.media.frame` exists.
https://github.com/emandiev/woo-image-seo/commit/7f109d9713a3d187565ff6488ede7752bf699fc4

The fix is live in version 1.2.3 of the plugin.
Please, let me know if the new version fixes the issue for you.
